#!/sbin/env bash

fd_args=""
[ ! -z "$1" ] && fd_args="-e ${1}"

cat ~/.document-registry \
    | xargs -0 -I{} expand-file-name "{}" \
    | xargs fd . ${fd_args} \
    | $(fuzzy-ui-provider -m) \
    | xargs -r -I{} d xdg-open "{}"
