#!/bin/bash

if [ -z "$1" ]; then
    echo 'Need to provide a file to add to.'
    exit 0
fi

TMP=$(mktemp --suffix=".org");
# TODO: Be nice to use elisp methods for this...
ORG_ENTRY="* "
echo "${ORG_ENTRY}" > $TMP

TMP_VIMSCRIPT=$(mktemp);
echo -n 'G A' > $TMP_VIMSCRIPT
i3.dd nvim -s "$TMP_VIMSCRIPT" $TMP
rm $TMP_VIMSCRIPT

FILE_CONTENTS="$(cat $TMP)"
rm $TMP

STRIPPED_CONTENTS="$(echo $FILE_CONTENTS | strip.all_whitespace)"
if [[ -z "$STRIPPED_CONTENTS" ]] || [[ "$STRIPPED_CONTENTS" = "$(echo $ORG_ENTRY | strip.all_whitespace)" ]]; then
    echo 'No idea captured.'
    exit 0
fi

echo "$FILE_CONTENTS" >> `resolve.home $1` 


# vim: ft=sh
