#!/bin/bash

CATALOG_DIRECTORY="${CATALOG_DIRECTORY:-"${HOME}/catalogs"}"

if [ ! -z "${CATALOG_DIRECTORY}" ]; then
  cd "${CATALOG_DIRECTORY}"
  fd -e yaml \
    | $(fuzzy-ui-provider) \
    | xargs -r realpath
fi

# vim: ft=sh
