#!/bin/bash

CATALOG="${1:-$(catalog-select)}"
LISTING_NAME="${2:-$(catalog-select-listing "${CATALOG}")}"

if [[ ! -z "${CATALOG}" ]] && [[ ! -z "${LISTING_NAME}" ]]; then
    yq -r '[ .listing[] | select(.name | contains("'"${LISTING_NAME}"'")) ] | first | .value' "${CATALOG}"
fi


# vim: ft=sh
