#!/usr/bin/env bash-ui-eval
# -*- mode: sh -*-

non_blocking=true
while true; do
  case "$1" in
    -w|--wait)
      non_blocking=false
      shift
      ;;
      *)
      break
      ;;
  esac
done

if [[ "$1" == "-" ]]; then
  command="e.stdin"
else
  command="${EDITOR:-vim} $@"
fi

if $non_blocking; then
    command="d ${command}"
fi

$command
