#!/usr/bin/env bash

ELISP="$@"
EXTRA_PARAMS=""
NO_FRAME="false"
CALL_INTERACTIVELY="false"
while true; do
  case "$1" in
    -nf|--no-frame)
      NO_FRAME="true"
      shift 1
      ;;
    -mx)
      CALL_INTERACTIVELY="true"
      shift 1
      ;;
      *)
      break
      ;;
  esac
done

if [ "${CALL_INTERACTIVELY}" = "true" ]; then
  ELISP="(funcall-interactively #'${1})"
fi


if [ "${NO_FRAME}" = "false" ]; then
  EXTRA_PARAMS+="-c "
fi

emacsdclient-bg $EXTRA_PARAMS -e "${ELISP}"
