#!/bin/bash

# Wait a max of 100s
sleep_length="0.1s"
max_tries=1000

# If there is no daemon.. let's try to get it started and then launch the client
if [ -z "$(pgrep -f 'emacs --daemon')" ]; then
  emacsd.start
fi

succeeded_in_launching=false
for try_n in $(seq $max_tries); do
  if [ -z "$(pgrep -f 'emacs --daemon')" ]; then
    sleep $sleep_length
    continue
  fi

  emacsclient "$@" && succeeded_in_launching=true
  break
done

if ! $succeeded_in_launching; then
  echo 'Error: emacs daemon had an issue starting up.' 1>&2
fi
