#!/bin/bash

EXTRA_PARAMS=""
while true; do
  case "$1" in
    -c)
      EXTRA_PARAMS="$1 "
      shift 1 
      ;;
      *)
      break
      ;;
  esac
done

if [ ! -z "$1" ]; then
  (nohup emacsclient $EXTRA_PARAMS -e "$1" &) > /dev/null 2>&1 
fi

# vim: ft=sh
