#!/bin/bash

COMMAND=""
ROFI_ARGS=""
FZF_ARGS="--height 10 --reverse"
MULTIPLE=false

while true; do
  case "$1" in
    --multiple | -m)
      MULTIPLE=true
      shift 
      ;;
    --rofi-args | -r)
      ROFI_ARGS="$2"
      shift 2
      ;;
    --fzf-args | -f)
      FZF_ARGS="$2"
      shift 2
      ;;
      *)
      break
      ;;
  esac
done

if [ "$(test.in_terminal)" = "true" ]; then
  COMMAND="fzf ${FZF_ARGS}"
  $MULTIPLE && COMMAND+=' -m'
else
  COMMAND="rofi -dmenu ${ROFI_ARGS}"
  $MULTIPLE && COMMAND+=' -multi-select'
fi

echo "${COMMAND}"

# vim: ft=sh
