#!/usr/bin/env php
<?php

function decode_jwt_payload($jwt) {
  $parts = explode('.', $jwt);
  $payload = str_replace(['-', '_'], ['+', '/'], $parts[1]);
  $payload = base64_decode($payload);
  $payload = json_encode(json_decode($payload), JSON_PRETTY_PRINT);
  return $payload;
}

if (!empty($argv[1])) {
  echo decode_jwt_payload($argv[1]); 
}

