#+TITLE: elisp
#+PROPERTY: header-args :tangle-relative 'dir :dir ${HOME}/.local/emacs/site-lisp

* Examples
:PROPERTIES:
:header-args:bash: :dir ~/Repositories/emacs-lisp-src :mkdirp t :tangle no
:END:

Finding examples of what other's are doing is always useful to me. Generally,
I have a search function =#'consult-rg-emacs-lisp-src=, which will search various
folders for emacs-lisp files. One of these is a 'third-party' style folder, which I
will maintain here. Run =C-c C-v s= to execute this subtree to set them all up
and update them (if they are setup for that)

** Doom emacs
I used doom for a while and a lot of my code comes from doom, so naturally, I want
to reference it!
#+CALL: git(SUBDIR="doom-emacs", REPO="https://github.com/hlissner/doom-emacs")
** Protesilaos Stavrou 
I appreciate Prot's content and emacs chops.

To start pull down all of his dotfiles
#+CALL: git[:dir ~/Repositories](SUBDIR="protesilaos-dotfiles", REPO="https://gitlab.com/protesilaos/dotfiles")

Then include the emacs-lisp parts
#+begin_src bash 
rm -f protesilaos
ln -s ~/Repositories/protesilaos-dotfiles/emacs/.emacs.d protesilaos
#+end_src

#+RESULTS:

** Spacemacs
#+CALL: git(SUBDIR="spacemacs", REPO="https://github.com/syl20bnr/spacemacs")
** abo-abo
#+CALL: git(SUBDIR="abo-abo", REPO="https://github.com/abo-abo/oremacs")

#+RESULTS:

** Howard Abrams
#+CALL: git(SUBDIR="howardabrams", REPO="https://github.com/howardabrams/dot-files")

#+RESULTS:

** jwiegley
#+CALL: git(SUBDIR="jwiegley", REPO="https://github.com/jwiegley/dot-emacs")
** IvanMalison
#+CALL: git(SUBDIR="IvanMalison", REPO="https://github.com/IvanMalison/dotfiles")

#+RESULTS:

** Joodie
#+CALL: git(SUBDIR="joodie", REPO="https://github.com/joodie/emacs-literal-config")
** expez
#+CALL: git(SUBDIR="expez", REPO="https://github.com/expez/.emacs.d")
** Purcell
#+CALL: git(SUBDIR="purcell", REPO="https://github.com/purcell/emacs.d")
** Prelude
#+CALL: git(SUBDIR="prelude", REPO="https://github.com/bbatsov/prelude")
** Emacs Doom Themes
#+CALL: git(SUBDIR="doom-themes", REPO="https://github.com/hlissner/emacs-doom-themes")
** Cabbage
#+CALL: git(SUBDIR="cabbage", REPO="https://github.com/senny/cabbage")
** Centaur Emacs
#+CALL: git(SUBDIR="centaur-emacs", REPO="https://github.com/seagle0128/.emacs.d")
** Better Defaults
#+CALL: git(SUBDIR="better-defaults", REPO="https://github.com/technomancy/better-defaults")
* Lib
#+NAME: git
#+begin_src bash :var SUBDIR="" REPO="" :dir ~/Repositories
[ -z "$REPO" -o -z "$SUBDIR" ] && exit

if [ ! -d $SUBDIR ]; then 
    git clone $REPO $SUBDIR
else
    cd $SUBDIR
    git pull
fi
#+end_src

#+RESULTS: git

* Extras
:PROPERTIES:
:header-args+: :tangle config-elisp.el
:END:
Extra elisp functionality that I find useful.
** Expressions
Allow for finding outermost sexps
#+BEGIN_SRC elisp
(defun beginning-of-sexp-p ()
  "Test if the point is at the beginning of a sexp."
  (= (point)
     (save-excursion
       (end-of-sexp)
       (beginning-of-sexp)
       (point))))

(defun outermost-list (&optional escape-strings no-syntax-crossing)
  "Move point to the end of the outermost list relative to the current point."
  (interactive "d\nd")
  ;; Don't ignore scan-error if we start at the wrong spot
  (up-list 1 escape-strings no-syntax-crossing)
  (ignore-error scan-error
    (cl-loop (up-list 1 escape-strings no-syntax-crossing))))

(defun end-of-outermost-sexp ()
  (interactive)
  (ignore-error scan-error
    (outermost-list t nil))
  (if (beginning-of-sexp-p)
      (end-of-sexp)))
#+END_SRC
** Meta Variables 
#+begin_src elisp
(defvar personal-elisp-packages (substitute-env-vars "$dot/tools/emacs/packages/"))
#+end_src
** Evaluation
Allow for different functions for eval-ing the sexp before the point.
#+begin_src elisp
(defvar elisp-eval-last-sexp-function #'eval-last-sexp)
#+end_src

Evaluate the sexp under the point (rather than needing to be at the end of the sexp).
#+BEGIN_SRC elisp
(defun eval-sexp-under-point (eval-last-sexp-arg-internal)
  (interactive "P")
  (with-syntax-table emacs-lisp-mode-syntax-table
    (save-excursion
      (end-of-sexp)
      (funcall elisp-eval-last-sexp-function eval-last-sexp-arg-internal))))
#+END_SRC

Adding evals for outer most sexp. Useful for =defun= and =let='s and the like.
#+BEGIN_SRC elisp
(defun eval-outermost-sexp (eval-last-sexp-arg-internal)
  "Evaluate outermost sexp, this utilizes the `elisp-eval-last-sexp-function'"
  (interactive "P")
  (with-syntax-table emacs-lisp-mode-syntax-table
    (save-excursion
      (end-of-outermost-sexp)
      (funcall elisp-eval-last-sexp-function eval-last-sexp-arg-internal))))

#+END_SRC

Helper function that let's me eval elisp in a notebook like fashion. I've not added any keybindings in the package definition here, but there are some in my doom config.
#+BEGIN_SRC elisp
(defun eval-outermost-sexp-and-continue (eval-last-sexp-arg-internal)
  "Attempts to evaluate outermost sexp. If it fails, move to next sexp.
This utilizes the `elisp-eval-last-sexp-function'."
  (interactive "P")
  (with-syntax-table emacs-lisp-mode-syntax-table
    (ignore-error end-of-file
      (eval-outermost-sexp eval-last-sexp-arg-internal))
    (end-of-outermost-sexp)
    (forward-sexp)
    (beginning-of-sexp))
  (recenter nil t))
#+END_SRC
** Eros 
Add a nice overlay when executing emacs lisp
#+begin_src elisp
(config! eros
         (setq elisp-eval-last-sexp-function #'eros-eval-last-sexp)
         (add-hook 'emacs-lisp-mode-hook 'eros-mode))
#+end_src
** Eval context
#+begin_src elisp
(require 'eval-context)
#+end_src
** Keybinding
#+begin_src elisp
;; Key-bindings
(keymap!
 (:map ctl-x-map
   ;; Replace 'elisp-eval-last-sexp-function
   :desc "Eval outermost sexp" "C-e" #'eval-outermost-sexp
   ;; Move 'elisp-eval-last-sexp-function
   "C-S-e" #'(lambda () (interactive) (funcall elisp-eval-last-sexp-function)))
 (:map emacs-lisp-mode-map
   :desc "Eval outermost sexp" "<S-return>" #'eval-outermost-sexp
   "<C-return>" #'eval-outermost-sexp-and-continue)
   :leader
    (:prefix-map ("e" . "edit/elisp")
     :desc "New elisp buffer" "b" (cmd
                                   (let ((default-directory personal-elisp-packages))
                                     (with-current-buffer (generate-new-buffer "*elisp*")
                                       (emacs-lisp-mode)
                                       (switch-to-buffer (current-buffer)))))
     (:prefix "H-e"
      :desc "Buffer context" "b" #'open-eval-context-buffer-buffer
      :desc "Debug context" "d" #'open-eval-context-edebug-buffer
      :desc "Set eval-context" "s" #'open-eval-context-buffer-debug
      :desc "Bufer repl" "r" #'open-repl-in-eval-context-buffer
      :desc "Debug repl ""R" #'open-repl-in-eval-context-edebug)))
#+end_src
** Hacks 
Evil doesn't play really well with some elisp navigating function... This corrects for it. Probably should push some of this upstream
#+begin_src elisp
(after! evil
    (defun evil/is-emulated-eol? ()
        "Determines if the point's current position is an emulated eol."
        (and (or (evil-normal-state-p)
                (evil-operator-state-p))
            (= (1+ (point))
                (line-end-position))))

    (defvar evil--should-correct-for-eol nil)

    (defadvice! evil/correct-eol--advice (fn &rest args)
        "Corrects the emulate eol for low level sexp / list functions.
This behavior is opt in only. Set '+evil--correct-eol--advice to t to
apply the correction."
        :around '(forward-sexp up-list)
        (when (and evil--should-correct-for-eol (evil/is-emulated-eol?))
        (forward-char))
        (apply fn args))

    (defadvice! elisp/correct-evil-emulate-eol (fn &rest args)
        "Outside of the emulated eol with forward sexp"
        :around '(beginning-of-sexp-p
                end-of-sexp-p
                outermost-list
                end-of-outermost-sexp
                eval-outermost-sexp
                eval-outermost-sexp-and-continue)
        (let ((evil--should-correct-for-eol t))
        (apply fn args))))
#+end_src
** Footer
#+BEGIN_SRC elisp
(provide 'config-elisp)
#+END_SRC
