#+TITLE: General
#+PROPERTY: header-args :tangle-relative 'dir

* Package Overview
** System packages
AKA 'site-lisp' directory. Installed under ~/usr/share/emacs/site-lisp~ on a unix system.
** User local packages
For me located at ~~/.local/emacs/site-lisp~, which is enabled via ~EMACSLOADPATH~
** Repo packages
For me located at ~$dot/tools/emacs/packages~, which is enabled via ~EMACSLOADPATH~
** User local "global" packages
These packages are installed by ~(require 'global-packages)~ found at ~~/.local/emacs/site-lisp/global-packages.el~ via =straight.el=.

* Site start
:PROPERTIES:
:header-args:elisp: :dir ${HOME}/.local/emacs/site-lisp :tangle site-start.el
:END:
#+BEGIN_SRC elisp
(provide 'site-start)

(when (string-equal system-type "android")
  (require 'config-android))
(require 'global-packages)
(require 'global-settings)
(require 'personal-lib)
(require 'config-keys)
(require 'config-ui)
#+END_SRC
* Config index
:PROPERTIES:
:header-args:elisp: :dir ${HOME}/.local/emacs/site-lisp :tangle config-main.el
:END:
Config packages (those prefixed with =config-=) should not 'do' anything by default.
They should simply provide /my/ configuration preferences for packages, so I can pull
them in anywhere. I may add methods to select which packages to use (and how they are
loaded). I am wanting to avoid loading any packages unless I actually decide I want them.

This might end up following the 'feature' / 'module' pattern that =doom-emacs= does, but
for now it's not so complex.
#+BEGIN_SRC elisp
(provide 'config-main)

(require! config-evil
          config-auth
          config-buffer
          config-email
          config-yank
          config-projects
          config-ui
          config-elisp
          config-ui-themes
          config-org
          config-org-ui
          config-org-babel
          config-org-latex
          config-org-export
          config-org-links
          config-org-remark
          config-selection-completion
          config-introspection
          config-editting
          config-pdf
          config-remote
          config-file-management
          config-window
          config-tab
          config-everywhere
          config-bookmark
          config-snippet
          config-searching
          config-notes
          config-processes
          config-programming)
#+END_SRC
