#+TITLE: Keyboard
#+PROPERTY: header-args :tangle-relative 'dir


* Finding out key info
If you need to find out key info use =wev=, it will tell you which the keycode for the key you are pressing. For help debugging issues with wayland and xkb install =libxkbcommon-tools= to get =xkbcli= and use =xkbcli interactive-wayland=
* Remap keys
I've tried to use xmodmap for this for a long time. Unfortunately it's not worked that well. Instead of that using =XKBOPTIONS= (see =man 7 xkeyboard-config=) for options. Specifically, I add the options I want to have them globally enabled in =/etc/default/keyboard=.

According to [[https://xkbcommon.org/doc/current/user-configuration.html][this]] documentation it should be possible to make the necessary changes within the user's directory, but I've not succeeding in getting that to take.

** Debug Notes
- To test out changes in the short term use =setxkbmap -option <option>=
- To see what options are set use =setxkbmap -query=

** Caps -> Hyper
To remaps caps to hyper for extra modifier. Use option:
=caps:hyper=

This will infact make hyper behave as an additional super. We have (potentially) a couple of files to modify to get this to work.

First we modify =/usr/share/X11/xkb/symbols/capslock=,  find the ="hyper"= block to set =CAPS= to =Mod3=.

#+begin_src text
hidden partial modifier_keys
xkb_symbols "hyper" {
    key <CAPS> { [ Hyper_L ], type[group1] = "ONE_LEVEL" };
    modifier_map Mod3 { <CAPS> };
};
#+end_src

Second we modify =/usr/share/X11/xkb/symbols/pc=,  find the instances of =<HYPR>= and make sure =<HYPR>= has not be added to =Mod4=, if it has change it =Mod3=.

** RAlt -> Compose
Set the right alt key to be the compose key allowing =<compose> " u= to generate =ü=. Use option:

=compose:ralt=


* Keyboard Configuator
For my system76 keyboard it's nice to use the keyboard configurator, which will require some setup on a non-Pop_OS! system. For linux see [[file:appimage.org][AppImage notes]]. [[https://github.com/pop-os/keyboard-configurator/releases][Releases]] can be found here.
